-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Creato il: Mar 19, 2024 alle 11:45
-- Versione del server: 10.4.24-MariaDB
-- Versione PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `piante`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `acquari`
--

CREATE TABLE `acquari` (
  `id_acquario` int(10) UNSIGNED NOT NULL,
  `litri` int(10) UNSIGNED NOT NULL,
  `larghezza` int(10) UNSIGNED NOT NULL,
  `lunghezza` int(10) UNSIGNED NOT NULL,
  `altezza` int(10) UNSIGNED NOT NULL,
  `descrizione` text DEFAULT 'descrizione non inserita'
) ;

-- --------------------------------------------------------

--
-- Struttura della tabella `immagini`
--

CREATE TABLE `immagini` (
  `id_immagine` int(10) UNSIGNED NOT NULL,
  `immagine_pianta` blob NOT NULL,
  `id_pianta` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Struttura della tabella `piante`
--

CREATE TABLE `piante` (
  `id_pianta` int(10) UNSIGNED NOT NULL,
  `nome` varchar(100) NOT NULL,
  `link_pagina` varchar(500) NOT NULL,
  `link_img` varchar(255) NOT NULL,
  `tipo` varchar(100) NOT NULL,
  `origine` varchar(100) NOT NULL,
  `tasso_crescita` enum('lento','medio','veloce') DEFAULT NULL,
  `altezza_minima` int(3) UNSIGNED NOT NULL,
  `altezza_massima` int(3) UNSIGNED NOT NULL,
  `luce` enum('poca','media','tanta') DEFAULT 'poca',
  `co2` enum('poca','media','tanta') DEFAULT 'poca',
  `link_logo` varchar(255) NOT NULL,
  `difficolta` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dump dei dati per la tabella `piante`
--

INSERT INTO `piante` (`id_pianta`, `nome`, `link_pagina`, `link_img`, `tipo`, `origine`, `tasso_crescita`, `altezza_minima`, `altezza_massima`, `luce`, `co2`, `link_logo`, `difficolta`) VALUES
(1, 'Aegagropila linnaei', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAegagropilalinnaei%28000CST%29%2F4385', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/000C ST/2.png&crop=resize&class=product', 'Moss', 'Cosmopolitan', 'lento', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(2, 'Aegagropila linnaei', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAegagropilalinnaei%28000DMP%29%2F19534', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/000D MP/2.png&crop=resize&class=product', 'Moss', 'Cosmopolitan', 'lento', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(3, 'Alternanthera reineckii \'Mini\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAlternantherareineckii%27Mini%27%28023CTC%29%2F4439', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/023C TC/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'medio', 5, 10, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(4, 'Alternanthera reineckii \'Pink\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAlternantherareineckii%27Pink%27%28023XL%29%2F4437', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/023 XL/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(5, 'Alternanthera reineckii \'Pink\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAlternantherareineckii%27Pink%27%28023%29%2F4436', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/023/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(6, 'Alternanthera reineckii \'Rosanervig\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAlternantherareineckii%27Rosanervig%27%28023D%29%2F4440', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/023D/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'medio', 5, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(7, 'Ammannia crassicaulis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAmmanniacrassicaulis%28033B%29%2F4449', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033B/2.png&crop=resize&class=product', 'Stem', 'Africa', 'medio', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(8, 'Anubias barteri ’Coin Leaf’', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarteri%E2%80%99CoinLeaf%E2%80%99%28101F%29%2F29447', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101F/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(9, 'Anubias barteri caladiifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbartericaladiifolia%28101UPCS%29%2F18816', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101U PCS/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(10, 'Anubias barteri \'Mini Coin\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarteri%27MiniCoin%27%28101BTC%29%2F28816', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101B TC/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(11, 'Anubias barteri nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterinana%28101TC%29%2F18895', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101 TC/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(12, 'Anubias barteri \'Petite\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarteri%27Petite%27%28101H%29%2F4554', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101H/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(13, 'Anubias barteri sp.', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterisp.%28101YWX%29%2F4549', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101 YWX/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(14, 'Anubias barteri var. barteri', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.barteri%28101A%29%2F4551', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101A/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(15, 'Anubias barteri var. caladiifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.caladiifolia%28101UXL%29%2F4557', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101U XL/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(16, 'Anubias barteri var. caladiifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.caladiifolia%28101U%29%2F4556', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101U/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(17, 'Anubias barteri var. \'Coffeifolia\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.%27Coffeifolia%27%28101G%29%2F4553', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101G/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(18, 'Anubias barteri var. glabra', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.glabra%28101C%29%2F4552', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101C/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(19, 'Anubias barteri var. nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%28101PCS%29%2F18806', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101 PCS/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(20, 'Anubias barteri var. nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%28101YLS%29%2F4546', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101 YLS/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(21, 'Anubias barteri var. nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%28101YWS%29%2F4548', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101 YWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(22, 'Anubias barteri var. nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%28101ZWS%29%2F4550', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101 ZWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(23, 'Anubias barteri var. nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%28101%29%2F4545', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(24, 'Anubias barteri var. nana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%28510YCS%29%2F28184', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/510 YCS/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(25, 'Anubias barteri var. nana ’Kirin’', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%E2%80%99Kirin%E2%80%99%28101K%29%2F29448', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101K/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(26, 'Anubias barteri var. nana ’Pinto’', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%E2%80%99Pinto%E2%80%99%28101E%29%2F29446', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101E/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 5, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(27, 'Anubias barteri var. nana \'Large\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasbarterivar.nana%27Large%27%28101L%29%2F19785', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101L/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(28, 'Anubias gracilis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAnubiasgracilis%28101D%29%2F17819', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/101D/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(29, 'Aponogeton boivinianus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAponogetonboivinianus%28088KN%29%2F4534', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/088 KN/2.png&crop=resize&class=product', 'Bulb/onion', 'Africa', 'veloce', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(30, 'Aponogeton longiplumulosus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAponogetonlongiplumulosus%28089DKN%29%2F4536', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/089D KN/2.png&crop=resize&class=product', 'Bulb/onion', 'Africa', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(31, 'Aponogeton madagascariensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAponogetonmadagascariensis%28089KN%29%2F4535', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/089 KN/2.png&crop=resize&class=product', 'Bulb/onion', 'Africa', 'medio', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(32, 'Aponogeton ulvaceus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FAponogetonulvaceus%28086KN%29%2F4533', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/086 KN/2.JPG&crop=resize&class=product', 'Bulb/onion', 'Africa', 'veloce', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(33, 'Bacopa australis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopaaustralis%28043A%29%2F4466', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/043A/2.png&crop=resize&class=product', 'Stem', 'South America', 'veloce', 5, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(34, 'Bacopa caroliniana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopacaroliniana%28043BDT%29%2F4465', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/043 BDT/2.png&crop=resize&class=product', 'Stem', 'North America', 'lento', 10, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(35, 'Bacopa caroliniana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopacaroliniana%28043MP%29%2F18811', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/043 MP/2.png&crop=resize&class=product', 'Stem', 'North America', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(36, 'Bacopa caroliniana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopacaroliniana%28043TC%29%2F18752', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/043 TC/2.JPG&crop=resize&class=product', 'Stem', 'North America', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(37, 'Bacopa caroliniana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopacaroliniana%28043%29%2F4464', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/043/2.png&crop=resize&class=product', 'Stem', 'North America', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(38, 'Bacopa monnieri \'Compact\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopamonnieri%27Compact%27%28044APCS%29%2F18800', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/044A PCS/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'veloce', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(39, 'Bacopa monnieri \'Compact\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBacopamonnieri%27Compact%27%28044A%29%2F4467', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/044A/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'veloce', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(40, 'Blyxa japonica', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBlyxajaponica%28057TC%29%2F22542', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/057 TC/2.JPG&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(41, 'Bolbitis heudelotii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBolbitisheudelotii%28006XL%29%2F18376', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/006 XL/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(42, 'Bolbitis heudelotii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBolbitisheudelotii%28006YWS%29%2F4407', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/006 YWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(43, 'Bolbitis heudelotii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBolbitisheudelotii%28006%29%2F4406', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/006/2.png&crop=resize&class=product', 'Rhizomatous', 'Africa', 'lento', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(44, 'Bucephalandra \'Kedagang\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandra%27Kedagang%27%28139BTC%29%2F22544', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139B TC/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(45, 'Bucephalandra \'Kedagang\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandra%27Kedagang%27%28139B%29%2F22543', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139B/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(46, 'Bucephalandra pygmaea \'Bukit Kelam\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandrapygmaea%27BukitKelam%27%28139TC%29%2F28393', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139 TC/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 5, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(47, 'Bucephalandra pygmaea \'Bukit Kelam\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandrapygmaea%27BukitKelam%27%28139%29%2F18757', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 5, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(48, 'Bucephalandra pygmaea \'Wavy Green\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandrapygmaea%27WavyGreen%27%28139YLS%29%2F18758', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139 YLS/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 5, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(49, 'Bucephalandra sp. \'Needle Leaf\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandrasp.%27NeedleLeaf%27%28139CTC%29%2F29517', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139C TC/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(50, 'Bucephalandra sp. \'Red\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FBucephalandrasp.%27Red%27%28139A%29%2F19682', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/139A/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 5, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(51, 'Cabomba aquatica', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCabombaaquatica%28015BDT%29%2F4431', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/015 BDT/2.png&crop=resize&class=product', 'Stem', 'South America', 'veloce', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(52, 'Cardamine lyrata', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCardaminelyrata%28024%29%2F4441', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/024/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 20, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(53, 'Ceratophyllum demersum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCeratophyllumdemersum%28021APOR%29%2F4434', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/021A POR/2.png&crop=resize&class=product', 'Stem', 'Cosmopolitan', 'veloce', 5, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(54, 'Ceratopteris thalictroides', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCeratopteristhalictroides%28005A%29%2F4405', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/005A/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'veloce', 15, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(55, 'Crinum calamistratum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCrinumcalamistratum%28094A%29%2F4541', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/094A/2.png&crop=resize&class=product', 'Bulb/onion', 'Africa', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(56, 'Crinum thaianum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCrinumthaianum%28093%29%2F4537', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/093/2.JPG&crop=resize&class=product', 'Bulb/onion', 'Asia', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(57, 'Cryptocoryne albida \'Brown\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynealbida%27Brown%27%28126B%29%2F18194', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/126B/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(58, 'Cryptocoryne beckettii \'Petchii\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynebeckettii%27Petchii%27%28108APCS%29%2F18807', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/108A PCS/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(59, 'Cryptocoryne beckettii \'Petchii\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynebeckettii%27Petchii%27%28108AYLS%29%2F4561', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/108A YLS/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(60, 'Cryptocoryne beckettii \'Petchii\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynebeckettii%27Petchii%27%28108A%29%2F4560', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/108A/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(61, 'Cryptocoryne crispatula', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynecrispatula%28125TC%29%2F18756', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/125 TC/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(62, 'Cryptocoryne crispatula', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynecrispatula%28125%29%2F4567', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/125/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(63, 'Cryptocoryne nurii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynenurii%28126TC%29%2F29518', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/126 TC/2.JPG&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(64, 'Cryptocoryne parva', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocoryneparva%28106TC%29%2F18755', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/106 TC/2.JPG&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 5, 10, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(65, 'Cryptocoryne parva', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocoryneparva%28106%29%2F4558', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/106/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 5, 10, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(66, 'Cryptocoryne undulata \'Broad Leaf\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocoryneundulata%27BroadLeaf%27%28110A%29%2F4566', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/110A/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(67, 'Cryptocoryne undulata \'Broad Leaf\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocoryneundulata%27BroadLeaf%27%28110BTC%29%2F19225', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/110B TC/2.JPG&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(68, 'Cryptocoryne usteriana', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocoryneusteriana%28120%29%2F18405', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/120/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(69, 'Cryptocoryne wendtii \'Green\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynewendtii%27Green%27%28109TC%29%2F19226', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/109 TC/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(70, 'Cryptocoryne wendtii \'Green\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynewendtii%27Green%27%28109%29%2F4562', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/109/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(71, 'Cryptocoryne wendtii \'Mi Oya\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynewendtii%27MiOya%27%28109DTC%29%2F19540', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/109D TC/2.JPG&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(72, 'Cryptocoryne wendtii \'Tropica\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynewendtii%27Tropica%27%28109EXL%29%2F4565', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/109E XL/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(73, 'Cryptocoryne wendtii \'Tropica\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynewendtii%27Tropica%27%28109E%29%2F4564', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/109E/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'medio', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(74, 'Cryptocoryne x willisii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynexwillisii%28107PCS%29%2F19618', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/107 PCS/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(75, 'Cryptocoryne x willisii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCryptocorynexwillisii%28107%29%2F4559', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/107/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(76, 'Cyperus helferi', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FCyperushelferi%28133A%29%2F4574', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/133A/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(77, 'Echinodorus \'Aquartica\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Aquartica%27%28074F%29%2F4526', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/074F/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 10, 20, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(78, 'Echinodorus cordifolius \'Fluitans\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodoruscordifolius%27Fluitans%27%28073D%29%2F4519', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/073D/2.png&crop=resize&class=product', 'Rosulate', 'North America', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(79, 'Echinodorus grisebachii \'Bleherae\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorusgrisebachii%27Bleherae%27%28071BDT%29%2F4513', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/071 BDT/2.png&crop=resize&class=product', 'Rosulate', 'South America', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(80, 'Echinodorus grisebachii \'Bleherae\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorusgrisebachii%27Bleherae%27%28071XL%29%2F21211', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/071 XL/2.JPG&crop=resize&class=product', 'Rosulate', 'South America', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(81, 'Echinodorus grisebachii \'Bleherae\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorusgrisebachii%27Bleherae%27%28071%29%2F4512', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/071/2.png&crop=resize&class=product', 'Rosulate', 'South America', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(82, 'Echinodorus \'Ozelot\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Ozelot%27%28073FXL%29%2F4521', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/073F XL/2.JPG&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(83, 'Echinodorus \'Ozelot\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Ozelot%27%28073F%29%2F4520', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/073F/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(84, 'Echinodorus \'Ozelot Green\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27OzelotGreen%27%28073G%29%2F4522', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/073G/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(85, 'Echinodorus palifolius', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodoruspalifolius%28076XL%29%2F4528', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/076 XL/2.JPG&crop=resize&class=product', 'Rosulate', 'South America', 'medio', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(86, 'Echinodorus palifolius', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodoruspalifolius%28076%29%2F4527', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/076/2.png&crop=resize&class=product', 'Rosulate', 'South America', 'medio', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(87, 'Echinodorus \'Red Diamond\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27RedDiamond%27%28074D%29%2F4525', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/074D/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 15, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(88, 'Echinodorus \'Reni\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Reni%27%28072DPCS%29%2F18818', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072D PCS/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(89, 'Echinodorus \'Reni\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Reni%27%28072DTC%29%2F18754', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072D TC/2.JPG&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(90, 'Echinodorus \'Reni\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Reni%27%28072D%29%2F4518', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072D/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(91, 'Echinodorus \'Rosé\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Ros%C3%A9%27%28072BXL%29%2F4517', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072B XL/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(92, 'Echinodorus \'Rosé\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorus%27Ros%C3%A9%27%28072B%29%2F4516', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072B/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(93, 'Echinodorus x barthii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorusxbarthii%28072AXL%29%2F4515', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072A XL/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(94, 'Echinodorus x barthii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEchinodorusxbarthii%28072A%29%2F4514', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/072A/2.png&crop=resize&class=product', 'Rosulate', 'Cultivar', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(95, 'Egeria densa', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEgeriadensa%28058BDT%29%2F4506', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/058 BDT/2.png&crop=resize&class=product', 'Stem', 'Cosmopolitan', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(96, 'Elatine hydropiper', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FElatinehydropiper%28141TC%29%2F18759', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/141 TC/2.png&crop=resize&class=product', 'Carpeting', 'Europe/Asia', 'medio', 3, 5, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(97, 'Eleocharis acicularis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEleocharisacicularis%28133TC%29%2F28401', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/133 TC/2.png&crop=resize&class=product', 'Stolon', 'Cosmopolitan', 'medio', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(98, 'Eleocharis montevidensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEleocharismontevidensis%28132D%29%2F4573', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/132D/2.png&crop=resize&class=product', 'Stolon', 'North America', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(99, 'Eleocharis parvula', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEleocharisparvula%28132C%29%2F4572', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/132C/2.png&crop=resize&class=product', 'Carpeting', 'Cosmopolitan', 'veloce', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(100, 'Eleocharis pusilla \'Mini\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEleocharispusilla%27Mini%27%28132BTC%29%2F4571', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/132B TC/2.JPG&crop=resize&class=product', 'Carpeting', 'Cultivar', 'lento', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(101, 'Eriocaulon cinereum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FEriocauloncinereum%28091TC%29%2F19547', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/091 TC/2.png&crop=resize&class=product', 'Rosulate', 'Cosmopolitan', 'lento', 3, 10, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(102, 'Fissidens fontanus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FFissidensfontanus%28002F%29%2F4390', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/002F/2.png&crop=resize&class=product', 'Moss', '', 'lento', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(103, 'Glossostigma elatinoides', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FGlossostigmaelatinoides%28045ATC%29%2F4470', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/045A TC/2.png&crop=resize&class=product', 'Carpeting', 'Australia', 'veloce', 3, 5, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(104, 'Gratiola viscidula', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FGratiolaviscidula%28042TC%29%2F18390', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/042 TC/2.JPG&crop=resize&class=product', 'Stem', 'North America', 'lento', 3, 10, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(105, 'Helanthium bolivianum \'Quadricostatus\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHelanthiumbolivianum%27Quadricostatus%27%28068TC%29%2F18896', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/068 TC/2.png&crop=resize&class=product', 'Rosulate', 'South America', 'veloce', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(106, 'Helanthium bolivianum \'Quadricostatus\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHelanthiumbolivianum%27Quadricostatus%27%28068%29%2F4511', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/068/2.png&crop=resize&class=product', 'Rosulate', 'South America', 'veloce', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(107, 'Helanthium tenellum \'Green\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHelanthiumtenellum%27Green%27%28067ATC%29%2F4757', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/067A TC/2.png&crop=resize&class=product', 'Carpeting', 'Cultivar', 'lento', 5, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(108, 'Hemianthus micranthemoides', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHemianthusmicranthemoides%28048ATC%29%2F22879', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/048A TC/2.JPG&crop=resize&class=product', 'Carpeting', 'North America', 'medio', 5, 15, 'media', 'media', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(109, 'Heteranthera zosterifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHeterantherazosterifolia%28096TC%29%2F4544', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/096 TC/2.JPG&crop=resize&class=product', 'Stem', 'South America', 'veloce', 20, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(110, 'Hottonia palustris', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHottoniapalustris%28027TC%29%2F28508', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/027 TC/2.JPG&crop=resize&class=product', 'Stem', 'Europe/Asia', 'medio', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(111, 'Hottonia palustris', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHottoniapalustris%28027%29%2F4443', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/027/2.png&crop=resize&class=product', 'Stem', 'Europe/Asia', 'medio', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(112, 'Hydrocotyle tripartita', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHydrocotyletripartita%28039BTC%29%2F18751', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/039B TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 5, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(113, 'Hydrocotyle tripartita', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHydrocotyletripartita%28039B%29%2F4458', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/039B/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 5, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(114, 'Hydrocotyle verticillata', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHydrocotyleverticillata%28039%29%2F4457', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/039/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 3, 10, 'tanta', 'media', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(115, 'Hygrophila corymbosa', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%28053BDT%29%2F4490', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053 BDT/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(116, 'Hygrophila corymbosa \'Compact\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%27Compact%27%28052D%29%2F18774', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/052D/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 10, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(117, 'Hygrophila corymbosa \'Siamensis 53B\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%27Siamensis53B%27%28053BMP%29%2F18813', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053B MP/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(118, 'Hygrophila corymbosa \'Siamensis 53B\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%27Siamensis53B%27%28053BPCS%29%2F18803', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053B PCS/2.JPG&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(119, 'Hygrophila corymbosa \'Siamensis 53B\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%27Siamensis53B%27%28053B%29%2F4493', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053B/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(120, 'Hygrophila corymbosa \'Stricta\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%27Stricta%27%28053AXL%29%2F4492', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053A XL/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(121, 'Hygrophila corymbosa \'Stricta\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacorymbosa%27Stricta%27%28053A%29%2F4491', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053A/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(122, 'Hygrophila costata', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilacostata%28052A%29%2F4489', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/052A/2.png&crop=resize&class=product', 'Stem', 'South America', 'veloce', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(123, 'Hygrophila difformis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophiladifformis%28051BDT%29%2F4485', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/051 BDT/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(124, 'Hygrophila lancea \'Araguaia\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilalancea%27Araguaia%27%28051BTC%29%2F4758', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/051B TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 10, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(125, 'Hygrophila pinnatifida', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilapinnatifida%28051ATC%29%2F19228', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/051A TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(126, 'Hygrophila pinnatifida', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilapinnatifida%28051A%29%2F4486', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/051A/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(127, 'Hygrophila pinnatifida', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilapinnatifida%28509YCS%29%2F28279', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/509 YCS/2.JPG&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(128, 'Hygrophila pinnatifida and moss', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilapinnatifidaandmoss%28051AYWS%29%2F4487', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/051A YWS/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(129, 'Hygrophila polysperma', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilapolysperma%28050%29%2F4483', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/050/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(130, 'Hygrophila polysperma \'Rosanervig\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FHygrophilapolysperma%27Rosanervig%27%28050B%29%2F4484', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/050B/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'medio', 20, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(131, 'Juncus repens', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FJuncusrepens%20%28133FTC%29%2F28107', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/133F TC/2.JPG&crop=resize&class=product', 'Stem', 'North America', 'medio', 10, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(132, 'Lagenandra meeboldii \'Red\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLagenandrameeboldii%27Red%27%28103%29%2F4759', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/103/2.png&crop=resize&class=product', 'Rosulate', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(133, 'Leptodictyum riparium', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLeptodictyumriparium%28003ETC%29%2F28671', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003E TC/2.JPG&crop=resize&class=product', 'Moss', 'Cosmopolitan', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(134, 'Lilaeopsis brasiliensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLilaeopsisbrasiliensis%28040PCS%29%2F18808', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/040 PCS/2.png&crop=resize&class=product', 'Stolon', 'South America', 'lento', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(135, 'Lilaeopsis brasiliensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLilaeopsisbrasiliensis%28040TC%29%2F4460', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/040 TC/2.png&crop=resize&class=product', 'Stolon', 'South America', 'lento', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(136, 'Lilaeopsis brasiliensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLilaeopsisbrasiliensis%28040%29%2F4459', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/040/2.png&crop=resize&class=product', 'Stolon', 'South America', 'lento', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(137, 'Limnobium laevigatum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLimnobiumlaevigatum%28063TC%29%2F4761', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/063 TC/2.png&crop=resize&class=product', 'Floating plant', 'South America', 'medio', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(138, 'Limnophila aquatica', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLimnophilaaquatica%28046%29%2F4471', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/046/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(139, 'Limnophila hippuridoides', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLimnophilahippuridoides%28047C%29%2F4474', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/047C/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(140, 'Limnophila sessiliflora', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLimnophilasessiliflora%28047MP%29%2F18812', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/047 MP/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(141, 'Limnophila sessiliflora', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLimnophilasessiliflora%28047PCS%29%2F18801', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/047 PCS/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png');
INSERT INTO `piante` (`id_pianta`, `nome`, `link_pagina`, `link_img`, `tipo`, `origine`, `tasso_crescita`, `altezza_minima`, `altezza_massima`, `luce`, `co2`, `link_logo`, `difficolta`) VALUES
(142, 'Limnophila sessiliflora', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLimnophilasessiliflora%28047%29%2F4472', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/047/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(143, 'Lindernia rotundifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLinderniarotundifolia%28045%29%2F4468', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/045/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 15, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(144, 'Littorella uniflora', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLittorellauniflora%28081TC%29%2F18269', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/081 TC/2.png&crop=resize&class=product', 'Stolon', 'Cosmopolitan', 'lento', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(145, 'Lobelia cardinalis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLobeliacardinalis%28053CMP%29%2F18840', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053C MP/2.png&crop=resize&class=product', 'Stem', 'North America', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(146, 'Lobelia cardinalis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLobeliacardinalis%28053CPCS%29%2F21134', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053C PCS/2.png&crop=resize&class=product', 'Stem', 'North America', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(147, 'Lobelia cardinalis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLobeliacardinalis%28053C%29%2F4494', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053C/2.png&crop=resize&class=product', 'Stem', 'North America', 'medio', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(148, 'Lobelia cardinalis \'Mini\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLobeliacardinalis%27Mini%27%28143TC%29%2F28647', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/143 TC/2.JPG&crop=resize&class=product', 'Stem', 'North America', 'medio', 3, 15, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(149, 'Ludwigia glandulosa', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLudwigiaglandulosa%28035A%29%2F4452', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/035A/2.png&crop=resize&class=product', 'Stem', 'North America', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(150, 'Ludwigia palustris \'Super Red\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLudwigiapalustris%27SuperRed%27%28035B%29%2F4453', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/035B/2.png&crop=resize&class=product', 'Stem', 'Cosmopolitan', 'medio', 10, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(151, 'Ludwigia repens \'Rubin\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FLudwigiarepens%27Rubin%27%28033D%29%2F4450', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033D/2.png&crop=resize&class=product', 'Stem', 'North America', 'medio', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(152, 'Marsilea hirsuta', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMarsileahirsuta%28010TC%29%2F4428', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/010 TC/2.png&crop=resize&class=product', 'Carpeting', 'Australia', 'medio', 5, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(153, 'Marsilea minuta', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMarsileaminuta%28010BTC%29%2F4762', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/010B TC/2.JPG&crop=resize&class=product', 'Carpeting', 'Asia', 'medio', 3, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(154, 'Mayaca fluviatilis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMayacafluviatilis%28140BDT%29%2F19792', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/140 BDT/2.png&crop=resize&class=product', 'Stem', 'North America', 'veloce', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(155, 'Micranthemum callitrichoides ´Cuba´', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumcallitrichoides%C2%B4Cuba%C2%B4%28048B%29%2F4477', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/048B/2.png&crop=resize&class=product', 'Carpeting', 'North America', 'medio', 3, 5, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(156, 'Micranthemum callitrichoides \'Cuba\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumcallitrichoides%27Cuba%27%28048BTC%29%2F4478', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/048B TC/2.JPG&crop=resize&class=product', 'Carpeting', 'North America', 'medio', 3, 5, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(157, 'Micranthemum glomeratum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumglomeratum%28048A%29%2F4476', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/048A/2.png&crop=resize&class=product', 'Carpeting', 'North America', 'medio', 5, 15, 'media', 'media', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(158, 'Micranthemum tweediei \'Monte Carlo\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumtweediei%27MonteCarlo%27%28025TC%29%2F4442', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/025 TC/2.png&crop=resize&class=product', 'Carpeting', 'South America', 'medio', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(159, 'Micranthemum tweediei \'Monte Carlo\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumtweediei%27MonteCarlo%27%28025%29%2F22880', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/025/2.png&crop=resize&class=product', 'Carpeting', 'South America', 'veloce', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(160, 'Micranthemum umbrosum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumumbrosum%28048ST%29%2F19793', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/048 ST/2.png&crop=resize&class=product', 'Stem', 'North America', '', 10, 15, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(161, 'Micranthemum umbrosum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicranthemumumbrosum%28048%29%2F4475', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/048/2.png&crop=resize&class=product', 'Stem', 'North America', 'veloce', 10, 15, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(162, 'Microsorum - Anubias \'Duet\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorum-Anubias%27Duet%27%28008NYWX%29%2F4427', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008N YWX/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 15, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(163, 'Microsorum pteropus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%28008XL%29%2F4409', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008 XL/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(164, 'Microsorum pteropus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%28008YLS%29%2F4410', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008 YLS/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(165, 'Microsorum pteropus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%28008YWS%29%2F4412', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008 YWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(166, 'Microsorum pteropus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%28008YWX%29%2F4413', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008 YWX/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(167, 'Microsorum pteropus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%28008%29%2F4408', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(168, 'Microsorum pteropus \'Narrow\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Narrow%27%28008APCS%29%2F18821', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008A PCS/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(169, 'Microsorum pteropus \'Narrow\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Narrow%27%28008AYWS%29%2F4415', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008A YWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(170, 'Microsorum pteropus \'Narrow\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Narrow%27%28008AZWS%29%2F4417', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008A ZWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(171, 'Microsorum pteropus \'Narrow\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Narrow%27%28008A%29%2F4414', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008A/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(172, 'Microsorum pteropus \'Trident\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Trident%27%28008GYWS%29%2F4425', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008G YWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 15, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(173, 'Microsorum pteropus \'Trident\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Trident%27%28008GZWM%29%2F4426', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008G ZWM/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 15, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(174, 'Microsorum pteropus \'Trident\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Trident%27%28008GZWS%29%2F19275', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008G ZWS/2.png&crop=resize&class=product', 'Rhizomatous', '', 'lento', 15, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(175, 'Microsorum pteropus \'Trident\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Trident%27%28008G%29%2F4424', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008G/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 15, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(176, 'Microsorum pteropus \'Windeløv\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Windel%C3%B8v%27%28008BYWS%29%2F4420', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008B YWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(177, 'Microsorum pteropus \'Windeløv\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Windel%C3%B8v%27%28008BYWX%29%2F4421', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008B YWX/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(178, 'Microsorum pteropus \'Windeløv\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Windel%C3%B8v%27%28008BZWM%29%2F4422', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008B ZWM/2.JPG&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(179, 'Microsorum pteropus \'Windeløv\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Windel%C3%B8v%27%28008BZWS%29%2F4423', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008B ZWS/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(180, 'Microsorum pteropus \'Windeløv\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumpteropus%27Windel%C3%B8v%27%28008B%29%2F4418', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/008B/2.png&crop=resize&class=product', 'Rhizomatous', 'Cultivar', 'lento', 10, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(181, 'Microsorum sp.', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMicrosorumsp.%28500OWX%29%2F4582', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/500 OWX/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'medio', 15, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(182, 'Monosolenium tenerum', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMonosoleniumtenerum%28002CTC%29%2F18747', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/002C TC/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(183, 'Murdannia keisak', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMurdanniakeisak%28135%29%2F4763', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/135/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 5, 20, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(184, 'Myriophyllum mattogrossense', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMyriophyllummattogrossense%28037TC%29%2F28108', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/037 TC/2.JPG&crop=resize&class=product', 'Stem', 'South America', 'veloce', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(185, 'Myriophyllum mattogrossense', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMyriophyllummattogrossense%28037%29%2F4454', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/037/2.JPG&crop=resize&class=product', 'Stem', 'South America', 'veloce', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(186, 'Myriophyllum sp. \'Guyana\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FMyriophyllumsp.%27Guyana%27%28037ETC%29%2F19549', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/037E TC/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 10, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(187, 'Nymphaea lotus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FNymphaealotus%28019%29%2F4432', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/019/2.png&crop=resize&class=product', 'Bulb/onion', 'Africa', 'medio', 20, 30, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(188, 'Nymphoides hydrophylla \'Taiwan\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FNymphoideshydrophylla%27Taiwan%27%28041BTC%29%2F4463', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/041B TC/2.png&crop=resize&class=product', 'Rhizomatous', 'Asia', 'veloce', 15, 10, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(189, 'Nymphoides hydrophylla \'Taiwan\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FNymphoideshydrophylla%27Taiwan%27%28041B%29%2F4462', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/041B/2.png&crop=resize&class=product', 'Bulb/onion', 'Asia', 'veloce', 15, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(190, 'Phyllanthus fluitans', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPhyllanthusfluitans%28028TC%29%2F22848', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/028 TC/2.JPG&crop=resize&class=product', 'Floating plant', 'South America', 'medio', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(191, 'Pogostemon deccanensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPogostemondeccanensis%28053FTC%29%2F4497', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053F TC/2.JPG&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(192, 'Pogostemon deccanensis', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPogostemondeccanensis%28053F%29%2F4496', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053F/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(193, 'Pogostemon helferi', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPogostemonhelferi%28053HTC%29%2F19680', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053H TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 3, 10, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(194, 'Pogostemon helferi', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPogostemonhelferi%28053HYLS%29%2F4500', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053H YLS/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 3, 10, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(195, 'Pogostemon helferi', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPogostemonhelferi%28053H%29%2F4499', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053H/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 3, 10, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(196, 'Pogostemon stellatus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FPogostemonstellatus%28053G%29%2F4498', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053G/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(197, 'Proserpinaca palustris \'Cuba\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FProserpinacapalustris%27Cuba%27%28037CTC%29%2F4766', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/037C TC/2.JPG&crop=resize&class=product', 'Stem', 'South America', 'medio', 10, 30, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(198, 'Ranunculus inundatus', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRanunculusinundatus%28022CTC%29%2F18225', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/022C TC/2.png&crop=resize&class=product', 'Stolon', 'Australia', 'medio', 5, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(199, 'Riccardia chamedryfolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRiccardiachamedryfolia%28003D%29%2F4400', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003D/2.png&crop=resize&class=product', 'Moss', 'Asia', 'lento', 3, 5, 'tanta', 'media', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(200, 'Riccia fluitans', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRicciafluitans%28001TC%29%2F4386', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/001 TC/2.png&crop=resize&class=product', 'Moss', 'Cosmopolitan', 'medio', 3, 5, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(201, 'Rotala indica \'Bonsai\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalaindica%27Bonsai%27%28033ETC%29%2F4451', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033E TC/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'lento', 5, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(202, 'Rotala macrandra', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalamacrandra%28032TC%29%2F4445', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/032 TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 20, 30, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(203, 'Rotala rotundifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalarotundifolia%28033MP%29%2F18810', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033 MP/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(204, 'Rotala rotundifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalarotundifolia%28033PCS%29%2F18799', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033 PCS/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(205, 'Rotala rotundifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalarotundifolia%28033%29%2F4447', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 15, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(206, 'Rotala rotundifolia \'Green\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalarotundifolia%27Green%27%28033ATC%29%2F22545', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/033A TC/2.JPG&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 20, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(207, 'Rotala rotundifolia \'H\'ra\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalarotundifolia%27H%27ra%27%28032CTC%29%2F19550', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/032C TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'veloce', 3, 20, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(208, 'Rotala wallichii', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FRotalawallichii%28032ATC%29%2F18748', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/032A TC/2.png&crop=resize&class=product', 'Stem', 'Asia', 'medio', 10, 30, 'tanta', 'tanta', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(209, 'Sagittaria subulata', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FSagittariasubulata%28079PCS%29%2F21135', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/079 PCS/2.png&crop=resize&class=product', 'Stolon', 'South America', 'veloce', 5, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(210, 'Sagittaria subulata', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FSagittariasubulata%28079TC%29%2F18270', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/079 TC/2.png&crop=resize&class=product', 'Stolon', 'South America', 'veloce', 5, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(211, 'Sagittaria subulata', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FSagittariasubulata%28079%29%2F4530', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/079/2.png&crop=resize&class=product', 'Stolon', 'South America', 'veloce', 5, 30, 'poca', 'media', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(212, 'Schismatoglottis prietoi', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FSchismatoglottisprietoi%28102TC%29%2F29519', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/102 TC/2.JPG&crop=resize&class=product', 'Stolon', 'Asia', 'medio', 3, 5, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(213, 'Shinnersia rivularis \'Weiss-Grün\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FShinnersiarivularis%27Weiss-Gr%C3%BCn%27%28053E%29%2F4495', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/053E/2.png&crop=resize&class=product', 'Stem', 'Cultivar', 'veloce', 10, 30, 'media', 'media', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(214, 'Staurogyne repens', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FStaurogynerepens%28049GPCS%29%2F19617', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/049G PCS/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(215, 'Staurogyne repens', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FStaurogynerepens%28049GTC%29%2F4482', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/049G TC/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(216, 'Staurogyne repens', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FStaurogynerepens%28049G%29%2F4481', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/049G/2.png&crop=resize&class=product', 'Stem', 'South America', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(217, 'Taxiphyllum alternans \'Taiwan Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumalternans%27TaiwanMoss%27%28003CTC%29%2F19551', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003C TC/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(218, 'Taxiphyllum barbieri \'Bogor Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumbarbieri%27BogorMoss%27%28003POR%29%2F4391', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003 POR/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(219, 'Taxiphyllum barbieri \'Bogor Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumbarbieri%27BogorMoss%27%28003TC%29%2F4393', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003 TC/2.JPG&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(220, 'Taxiphyllum barbieri \'Bogor Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumbarbieri%27BogorMoss%27%28003YLS%29%2F4394', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003 YLS/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(221, 'Taxiphyllum sp. ’Flame Moss’', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumsp.%E2%80%99FlameMoss%E2%80%99%28003HTC%29%2F4403', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003H TC/2.JPG&crop=resize&class=product', 'Moss', 'Asia', 'lento', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(222, 'Taxiphyllum sp. \'Spiky Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumsp.%27SpikyMoss%27%28003GPOR%29%2F4402', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003G POR/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(223, 'Taxiphyllum sp. \'Spiky Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FTaxiphyllumsp.%27SpikyMoss%27%28003GTC%29%2F18271', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003G TC/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 10, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(224, 'Utricularia graminifolia', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FUtriculariagraminifolia%28049BTC%29%2F4480', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/049B TC/2.png&crop=resize&class=product', 'Carpeting', 'Asia', 'medio', 3, 10, 'media', 'media', '/Graphics/Web/icon_difficulty_Advanced.png', 'Advanced.png'),
(225, 'Vallisneria americana \'Gigantea\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVallisneriaamericana%27Gigantea%27%28054%29%2F4501', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/054/2.JPG&crop=resize&class=product', 'Stolon', 'Asia', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(226, 'Vallisneria spiralis \'Tiger\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVallisneriaspiralis%27Tiger%27%28055A%29%2F4503', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/055A/2.png&crop=resize&class=product', 'Stolon', 'Asia', 'veloce', 20, 30, 'poca', 'poca', '/Graphics/Web/icon_difficulty_Easy.png', 'Easy.png'),
(227, 'Vesicularia ferriei \'Weeping Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVesiculariaferriei%27WeepingMoss%27%28003BPOR%29%2F4398', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003B POR/2.png&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(228, 'Vesicularia ferriei \'Weeping Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVesiculariaferriei%27WeepingMoss%27%28003BTC%29%2F4399', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003B TC/2.JPG&crop=resize&class=product', 'Moss', 'Asia', 'medio', 3, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(229, 'Vesicularia montagnei \'Christmas\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVesiculariamontagnei%27Christmas%27%28003AYWS%29%2F4397', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003A YWS/2.png&crop=resize&class=product', 'Moss', 'South America', 'medio', 3, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(230, 'Vesicularia montagnei \'Christmas Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVesiculariamontagnei%27ChristmasMoss%27%28003APOR%29%2F4395', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003A POR/2.png&crop=resize&class=product', 'Moss', 'South America', 'medio', 3, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png'),
(231, 'Vesicularia montagnei \'Christmas Moss\'', 'https%3A%2F%2Ftropica.com%2F%2Fen%2Fplants%2Fplantdetails%2FVesiculariamontagnei%27ChristmasMoss%27%28003ATC%29%2F4396', 'https://tropica.com/imagegen.ashx?width=200&image=/Plants/003A TC/2.JPG&crop=resize&class=product', 'Moss', 'South America', 'medio', 3, 5, 'media', 'poca', '/Graphics/Web/icon_difficulty_Medium.png', 'Medium.png');

-- --------------------------------------------------------

--
-- Struttura della tabella `piante_acquari`
--

CREATE TABLE `piante_acquari` (
  `id_pianta` int(10) UNSIGNED NOT NULL,
  `id_acquario` int(10) UNSIGNED NOT NULL,
  `quantita` int(10) UNSIGNED DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `acquari`
--
ALTER TABLE `acquari`
  ADD PRIMARY KEY (`id_acquario`);

--
-- Indici per le tabelle `immagini`
--
ALTER TABLE `immagini`
  ADD PRIMARY KEY (`id_immagine`),
  ADD KEY `imm_pia` (`id_pianta`);

--
-- Indici per le tabelle `piante`
--
ALTER TABLE `piante`
  ADD PRIMARY KEY (`id_pianta`);

--
-- Indici per le tabelle `piante_acquari`
--
ALTER TABLE `piante_acquari`
  ADD PRIMARY KEY (`id_pianta`,`id_acquario`),
  ADD KEY `piac_acq` (`id_acquario`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `acquari`
--
ALTER TABLE `acquari`
  MODIFY `id_acquario` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT per la tabella `immagini`
--
ALTER TABLE `immagini`
  MODIFY `id_immagine` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT per la tabella `piante`
--
ALTER TABLE `piante`
  MODIFY `id_pianta` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=232;

--
-- Limiti per le tabelle scaricate
--

--
-- Limiti per la tabella `immagini`
--
ALTER TABLE `immagini`
  ADD CONSTRAINT `imm_pia` FOREIGN KEY (`id_pianta`) REFERENCES `piante` (`id_pianta`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Limiti per la tabella `piante_acquari`
--
ALTER TABLE `piante_acquari`
  ADD CONSTRAINT `piac_acq` FOREIGN KEY (`id_acquario`) REFERENCES `acquari` (`id_acquario`) ON UPDATE CASCADE,
  ADD CONSTRAINT `piac_pia` FOREIGN KEY (`id_pianta`) REFERENCES `piante` (`id_pianta`) ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
